### PR TITLE
Implement initial test enviro

### PR DESCRIPTION
**Pull request by bmalamudroam**
Unit tests written for app rendering as expected both pre and post initial state recovery. Also outlined further unit tests which can be implemented

### CODE REVIEW

**Comment by bmalamudroam** [comment]
@DigitalDsntHurt  @AnimalFace  Not too urgent with this one, get to it when you can.

**Review by DigitalDsntHurt — APPROVED** [review]
Are you writing all your component tests in a single file?
Even if so, react.test.jsx strikes me as a slightly sketchy / non-descript name for a test file. 
nice tho

**Review by DigitalDsntHurt — APPROVED** [review]
Are you writing all your component tests in a single file?
Even if so, react.test.jsx strikes me as a slightly sketchy / non-descript name for a test file. 
nice tho

**Comment by bmalamudroam** [comment]
@DigitalDsntHurt It's definitely a bit vague, could clean it up. I'll do a new ticket for separating and specifying test files

**Pull request merged**
